## Add new product
POST http://localhost:4002/product
content-type: application/json

{
    "name": "iPhone 13",
    "price": 9000
}

### Gets list of products
GET http://localhost:4002/products

### Get product by Id
GET http://localhost:4002/product/:id

### Update product info
PUT http://localhost:4002/product/:id
content-type: application/json

{
    "price": 10000
}

### Deletes a products
DELETE http://localhost:4002/product/:id